networks:
  monitoring:
    driver: bridge
  sneakdex-network:
    driver: bridge

volumes:
  grafana-data:
  kafka-data:
  prometheus-data:
  redis-data:

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: sneakdex-kafka
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_MESSAGE_MAX_BYTES=10485760
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=10485760
      # Enable JMX for metrics
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_JMX_PORT=9999
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - monitoring
      - sneakdex-network
    healthcheck:
      test:
        ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 0.0.0.0:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: sneakdex-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - monitoring
      - sneakdex-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  crawler:
    build:
      context: ./services/crawler
      dockerfile: Dockerfile
    # For Air live reload, enable init to true
    init: true
    environment:
      - CRAWL_DEPTH=3
      - ENABLE_DEBUG=false
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_RETRY_MAX=3
      - KAFKA_TOPIC_HTML=raw-html
      - LOG_LEVEL=info
      - MAX_CONCURRENCY=16
      - MAX_CONTENT_SIZE=10485760 # 10 MB
      - MAX_PAGES=10000
      - MONITOR_PORT=8080
      - REDIS_DB=0
      - REDIS_HOST=redis
      - REDIS_PASSWORD=""
      - REDIS_PORT=6379
      - REDIS_RETRY_MAX=3
      - REDIS_TIMEOUT=5s
      - REQUEST_DELAY=50ms
      - REQUEST_TIMEOUT=10s
      - START_URLS=https://en.wikipedia.org/wiki/Special:Random,https://simple.wikipedia.org/wiki/Special:Random,https://news.ycombinator.com,https://www.reuters.com/news/archive/worldNews,https://www.bbc.com/news,https://github.com/trending,https://stackoverflow.com/questions,https://dev.to,https://developer.mozilla.org/en-US/docs/Web,https://arxiv.org/list/cs/new,https://eng.uber.com,https://netflixtechblog.com,https://blog.cloudflare.com,https://www.dhruvrishishwar.com
      - USER_AGENT=Sneakdex/1.0
    volumes:
      - ./services/crawler/cmd:/app/cmd
      - ./services/crawler/internal:/app/internal
      - ./services/crawler/.air.toml:/app/.air.toml
      - ./services/crawler/go.mod:/app/go.mod
      - ./services/crawler/go.sum:/app/go.sum
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - monitoring
      - sneakdex-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1000s
    restart: unless-stopped

  parser:
    build:
      context: ./services/parser
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_GROUP_ID=parser-group
      - KAFKA_TOPIC_HTML=raw-html
      - KAFKA_TOPIC_PARSED=parsed-pages
      - MAX_CONCURRENCY=64
      - MAX_CONTENT_LENGTH=5242880 # 5 MB
      - MIN_CONTENT_LENGTH=1024 # 1 KB
      - MONITOR_PORT=8080
      - RUST_LOG=info
    volumes:
      - ./services/parser:/app
      - /app/target
    depends_on:
      kafka:
        condition: service_healthy
      crawler:
        condition: service_started
    networks:
      - monitoring
      - sneakdex-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1000s
    restart: unless-stopped

  indexer:
    build:
      context: ./services/indexer
      dockerfile: Dockerfile
    container_name: sneakdex-indexer
    environment:
      - BATCH_SIZE=500
      - INDEX_OUTPUT_PATH=/app/data/index
      - INDEX_SAVE_INTERVAL=5000
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_GROUP_ID=indexer-group
      - KAFKA_TOPIC_PARSED=parsed-pages
      - MAX_DOCS=10000
      - MAX_FEATURES=100000
      - MONITOR_PORT=8080
      - NUM_CONSUMER_THREADS=2
      - NUM_WORKER_THREADS=4
      - PREPROCESSING_WORKERS=4
      - PYTHON_ENV=development
      - TF_IDF_MIN_DF=2
    volumes:
      - ./services/indexer/indexer:/app/indexer
      - ./services/indexer/requirements.txt:/app/requirements.txt
    depends_on:
      kafka:
        condition: service_healthy
      parser:
        condition: service_started
    networks:
      - monitoring
      - sneakdex-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1000s
    restart: unless-stopped

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: sneakdex-app
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./app:/app
    depends_on:
      indexer:
        condition: service_started
    networks:
      - monitoring
      - sneakdex-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 120s
    restart: unless-stopped

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    command:
      - "--kafka.server=kafka:9092"
      - "--web.listen-address=:9308"
    networks:
      - sneakdex-network
      - monitoring
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    ports:
      - "9121:9121"
    command:
      - "--redis.addr=redis://redis:6379"
    networks:
      - monitoring
      - sneakdex-network
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    networks:
      - sneakdex-network
      - monitoring
    depends_on:
      kafka-exporter:
        condition: service_started
      redis-exporter:
        condition: service_started
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=sneaky
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    restart: unless-stopped
