global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape Redis Exporter
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # Scrape Kafka Exporter
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "crawler-dev"
    static_configs:
      - targets:
          - "sneakdex-crawler-dev-1:8080"
          - "sneakdex-crawler-dev-2:8080"
          - "sneakdex-crawler-dev-3:8080"
          - "sneakdex-crawler-dev-4:8080"
          - "sneakdex-crawler-dev-5:8080"

  - job_name: "parser-dev"
    static_configs:
      - targets:
          - "sneakdex-parser-dev-1:8080"
          - "sneakdex-parser-dev-2:8080"
          - "sneakdex-parser-dev-3:8080"
