global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape Redis Exporter
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # Scrape Kafka Exporter
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  # Scrape crawler-dev replicas (dynamic ports if scaled with --scale)
  - job_name: "crawler-dev"
    dns_sd_configs:
      - names:
          - "crawler-dev"
        type: "A"
        port: 8090
        refresh_interval: 30s
