global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape Redis Exporter
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # Scrape Kafka Exporter
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "crawler-prod"
    static_configs:
      - targets:
          - "sneakdex-crawler-prod-1:8080"
          - "sneakdex-crawler-prod-2:8080"
          - "sneakdex-crawler-prod-3:8080"

  - job_name: "parser-prod"
    static_configs:
      - targets:
          - "sneakdex-parser-prod-1:8080"
          - "sneakdex-parser-prod-2:8080"
          - "sneakdex-parser-prod-3:8080"

  - job_name: "sneakdex-indexer-prod"
    static_configs:
      - targets: ["sneakdex-indexer-prod:8080"]

  - job_name: "sneakdex-app-prod"
    static_configs:
      - targets: ["sneakdex-app-prod:3000"]
