global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape Redis Exporter
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # Scrape Kafka Exporter
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  # Scrape Crawler instances
  - job_name: "crawler"
    static_configs:
      - targets:
          - "sneakdex-crawler-1:8080"
        labels:
          instance_id: "crawler-1"
          service: "crawler"
      - targets:
          - "sneakdex-crawler-2:8080"
        labels:
          instance_id: "crawler-2"
          service: "crawler"
      - targets:
          - "sneakdex-crawler-3:8080"
        labels:
          instance_id: "crawler-3"
          service: "crawler"
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s

  # Scrape Parser instances
  - job_name: "parser"
    static_configs:
      - targets:
          - "sneakdex-parser-1:8080"
        labels:
          instance_id: "parser-1"
          service: "parser"
      - targets:
          - "sneakdex-parser-2:8080"
        labels:
          instance_id: "parser-2"
          service: "parser"
      - targets:
          - "sneakdex-parser-3:8080"
        labels:
          instance_id: "parser-3"
          service: "parser"
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s

  # Scrape Indexer
  - job_name: "indexer"
    static_configs:
      - targets:
          - "sneakdex-indexer-1:8080"
        labels:
          instance_id: "indexer-1"
          service: "indexer"
      - targets:
          - "sneakdex-indexer-2:8080"
        labels:
          instance_id: "indexer-2"
          service: "indexer"
      - targets:
          - "sneakdex-indexer-3:8080"
        labels:
          instance_id: "indexer-3"
          service: "indexer"
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s

  # Scrape Next.js App
  - job_name: "sneakdex-app"
    static_configs:
      - targets: ["sneakdex-app:3000"]
        labels:
          service: "app"
    metrics_path: "/api/metrics"
    scrape_interval: 30s
    scrape_timeout: 15s