global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape Redis Exporter
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # Scrape Kafka Exporter
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  # Scrape Crawler-prod instances
  - job_name: "crawler-prod"
    static_configs:
      - targets:
          - "sneakdex-crawler-prod-1:8080"
        labels:
          instance_id: "crawler-prod-1"
          service: "crawler-prod"
      - targets:
          - "sneakdex-crawler-prod-2:8080"
        labels:
          instance_id: "crawler-prod-2"
          service: "crawler-prod"
      - targets:
          - "sneakdex-crawler-prod-3:8080"
        labels:
          instance_id: "crawler-prod-3"
          service: "crawler-prod"
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s

  # Scrape Parser-prod instances
  - job_name: "parser-prod"
    static_configs:
      - targets:
          - "sneakdex-parser-prod-1:8080"
        labels:
          instance_id: "parser-prod-1"
          service: "parser-prod"
      - targets:
          - "sneakdex-parser-prod-2:8080"
        labels:
          instance_id: "parser-prod-2"
          service: "parser-prod"
      - targets:
          - "sneakdex-parser-prod-3:8080"
        labels:
          instance_id: "parser-prod-3"
          service: "parser-prod"
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s

  # Scrape Indexer-prod
  - job_name: "indexer-prod"
    static_configs:
      - targets:
          - "sneakdex-indexer-prod-1:8080"
        labels:
          instance_id: "indexer-prod-1"
          service: "indexer-prod"
      - targets:
          - "sneakdex-indexer-prod-2:8080"
        labels:
          instance_id: "indexer-prod-2"
          service: "indexer-prod"
      - targets:
          - "sneakdex-indexer-prod-3:8080"
        labels:
          instance_id: "indexer-prod-3"
          service: "indexer-prod"
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s

  # Scrape Next.js App-prod
  - job_name: "sneakdex-app-prod"
    static_configs:
      - targets: ["sneakdex-app-prod:3000"]
        labels:
          service: "app"
    metrics_path: "/api/metrics"
    scrape_interval: 30s
    scrape_timeout: 15s