root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/crawler"
  cmd = "go build -o ./tmp/crawler ./cmd/crawler"
  delay = 500
  exclude_dir = ["tmp", "vendor", "data"]
  exclude_regex = ["_test.go"]
  include_ext = ["go"]
  kill_delay = "2s"
  send_interrupt = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true